# Generated by Django 5.1.2 on 2024-11-06 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eob_website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualuser',
            name='organization_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
