# Generated by Django 5.1.2 on 2024-11-08 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eob_website', '0002_individualuser_organization_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='material',
            old_name='material',
            new_name='material_type',
        ),
        migrations.AddField(
            model_name='material',
            name='folder_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eob_website.category'),
        ),
    ]
