# Generated by Django 5.1.2 on 2024-11-11 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eob_website', '0003_materialcategory_softwarecategory_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SoftwareCategory',
        ),
    ]
