# Generated by Django 5.1.3 on 2024-11-15 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eob_website', '0005_material_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='folder_type',
        ),
    ]
