# Generated by Django 5.1.3 on 2024-11-15 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eob_website', '0006_remove_folder_folder_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='can_upload',
            field=models.BooleanField(default=False),
        ),
    ]
