# Generated by Django 5.1.3 on 2024-11-20 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eob_website', '0009_remove_material_preview_image_filepreviewimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='color',
        ),
    ]
