# Generated by Django 5.1.3 on 2024-12-03 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eob_website', '0010_remove_material_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewpost',
            name='post_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
