# Generated by Django 5.1.3 on 2024-12-04 03:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eob_website', '0011_reviewpost_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewpost',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
