# Generated by Django 5.1.3 on 2024-12-04 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eob_website', '0012_reviewpost_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewpost',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
